"""Added  game model

Revision ID: e93f4859ee06
Revises: ff9c8bedb479
Create Date: 2023-12-13 20:28:50.709450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93f4859ee06'
down_revision: Union[str, None] = 'ff9c8bedb479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventure_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attacker_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starting_health', sa.Integer(), nullable=True),
    sa.Column('current_health', sa.Integer(), nullable=True),
    sa.Column('damage_points', sa.Integer(), nullable=True),
    sa.Column('adventure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avatars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('health_points', sa.Integer(), nullable=True),
    sa.Column('damage_points', sa.Integer(), nullable=True),
    sa.Column('last_health_points', sa.Integer(), nullable=True),
    sa.Column('last_damage_points', sa.Integer(), nullable=True),
    sa.Column('adventure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatars')
    op.drop_table('attacker_table')
    op.drop_table('adventure_table')
    # ### end Alembic commands ###
